#!/bin/sh

OLD_MAC_ADDRESS="$(ifconfig wlp4s0 | grep ether | grep -oE [0-9abcdef:]{17})"
NEW_MAC_ADDRESS="$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//')"

echo Old MAC Address: $OLD_MAC_ADDRESS

sudo ifconfig wlp4s0 down
sudo ifconfig wlp4s0 hw ether $NEW_MAC_ADDRESS
sudo ifconfig wlp4s0 up

echo MAC address successfully changed
echo New MAC Address: $NEW_MAC_ADDRESS
